services:
  inference:
    container_name: inference-hf-sunny18
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u /app/app.py
    ports:
      - "8018:8018"

  worker-sunny18:
    container_name: worker-sunny18
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    depends_on:
      - inference
    env_file:
      - ./worker-data/env_file
  
volumes:
  inference-data:
  worker-data:
